### ISSUE TITLE
withLazyLoading don't work with StackNavigator

### ISSUE THREAD

**Issue by lucianomlima** [Ajith-Pandian/ReactNavigationUtils#2]
When I try to pass a StackNavigator as screen for a Tab route like below
```jsx
const ProfileNav = StackNavigator({
    route1: {},
    route2: {}
});

const ProfileScreen = withLazyLoading(ProfileNav);
const Tabs = TabNavigator({
    tab1: {},
    tab2: ProfileScreen
});
```

I get an error `TypeError: Cannot read property 'forEach' of undefined`.
If I remove withLazyLoading and pass navigator directly, works fine.

**Comment by kidequinox** [comment]
+1
